eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: http://localhost:9002
          predicates:
            - Path=/api/v1/students/**
        - id: schools
          uri: http://localhost:9001
          predicates:
            - Path=/api/v1/schools/**
